[package]
name = "rust_act"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7"
ariadne = "0.1.2"
expect-test = "1.2.2"
static_assertions = "1.1.0"
nom-supreme = "0.6.0"
pretty = "0.11.3"
itertools="0.10.3"
